#!/bin/sh
# $Revision$, $Date$ 

# simple script that converts SGML-docbook references
# using Steve Cheng's docbooc2man-spec perl converter
# in case of <refentry lang="pl"> translates NAME and SYNOPSIS

DIR="/usr/share/docbook2X"
SPEC=$DIR/docbook2man-spec.pl
MKLINKS=$DIR/manpage_makelinks.pl
PROGNAME=`basename $0`

clean() {
#	rm -f manpage.links
}


if [ -x /usr/bin/onsgmls ]; then
        SP=onsgmls;              
else if [ -x /usr/bin/nsgmls ]; then
        SP=nsgmls;              
else
        echo "$PROGNAME: SGML parser missing";
        exit;
fi
fi

if [ $# -eq 0 ]; then
        echo "$PROGNAME: No input file given";
        exit;
fi

# TODO option passing to spec
#while test $# -gt 0 ; do
#    case "${1}" in
#        --*)
#            OPTIONS="$OPTIONS ${1}"; shift ;;
#	*)
#	    break; # stop at first non-option stri
#    esac
#done
#
#echo LASTARGNO=$(($#-1))
#echo FILENAME=${$LASTARGNO} # last argument must be filename
#${(($#-1))}="" # delete filename from arg list


if [ ! -f "$1" ]; then
        echo "$PROGNAME: Unable to open file $1";
        exit;
fi

$SP "$1" |sgmlspl $SPEC    # $@

$MKLINKS < manpage.links



# $Log$
# Revision 1.4  2000/06/23 00:19:20  klakier
# - small fix
#
# Revision 1.3  2000/02/26 15:17:57  klakier
# - more test against missing arguments, files, etc
#
# Revision 1.2  2000/01/20 14:41:08  klakier
# - I forgot to commit it ... I dont remember
#
# Revision 1.1  1999/12/29 15:59:47  klakier
# - wrapper script for Steve Cheng's docbook2man-spec converter
#  
